### ISSUE TITLE
Question on multiple api calls

### ISSUE THREAD

**Issue by realrk95** [eneural-net/async_task#17]
I want to run several API calls in parallel. Each API yields around 300,000 rows and about 32 pages in total. It takes 30 mins currently. I need to get it below 5 mins. Each request takes about 40 seconds individually and bas about 50 mb of data (on average). Any clue on how to do this?

I've been looking for a decent implementation for some time now. This package will be very useful for backend stuff (especially cron jobs). Thanks devs!

**Comment by gmpassos** [comment]
It all depends on how many cores your "server" has.

Note that the parameter 'parallelism' at 'AsyncExecutor' shouldn't be greater than the CPU cores.
