### ISSUE TITLE
how to use with streams

### ISSUE THREAD

**Issue by deadsoul44** [eneural-net/async_task#2]
Thank you for the great package.

I saw your packages from your comment in this issue:
https://github.com/dart-lang/sdk/issues/36097#issuecomment-871281712

I also have a use case for Dart Isolates. I tried to describe it in the same issue after your comment:
https://github.com/dart-lang/sdk/issues/36097#issuecomment-871544816

I was thinking that if I should use this package and listen to Firestore stream in the main thread and compute each response as an async_task or somehow is it possible to use this package in order to listen to Firestore stream in a completely separate isolate and only send custom objects to main thread?

**Comment by gmpassos** [comment]
I think that the use of `AsyncTaskChannel ` with `AsyncTask` is what you want.
https://pub.dev/packages/async_task#asynctaskchannel

If you need any help to use just send here. Maybe I need to add an example for that and you can help me to create one.

**Comment by deadsoul44** [comment]
Should I initialize Firestore in the main thread and use async_task at each firing event? Or is it possible to do something like stream_task to initialize Firestore inside, do all the computations and send only the final result to main thread. Becuase, sending data to isolate at each firing event may freeze UI. Or is this solved by this package already? By the way, stream fires once every minute and the result is used in ListView so performance is critical for smooth scroll.

**Comment by gmpassos** [comment]
I think that you won't be able to send an initialized Firestore through Isolate, and you will need it for requests inside spawned Isolate.

You can create an `AsyncTask`, that initialized `Firestore` and has a loop reading messages from `AsyncTaskChannel`, processing the requests and sending the response.
