### ISSUE TITLE
Example using AsyncTask for fetching remote data

### ISSUE THREAD

**Issue by dtvtkien** [eneural-net/async_task#3]
Could you create an example about API fetching? For example, I have a Weather repository class to handle Weather APIs, that depends on a [dio](https://pub.dev/packages/dio) instance. How could I use AsyncTask to get weather from a city (API that need dio instance and locationId)?

**Comment by gmpassos** [comment]
Take a look at `async_field`:

https://pub.dev/packages/async_field

There's an example fetching Bitcoin x USD price:

https://pub.dev/packages/async_field/example
