### ISSUE TITLE
Working with generics

### ISSUE THREAD

**Issue by tomasweigenast** [eneural-net/async_task#9]
Hi. I just wordering how this can work with generic tasks.
Because the following:
```dart
List<AsyncTask> _taskTypeRegister() => [
  _FuzzySearchTask(_FuzzySearchTaskArgs(tokenSearchers: const [], fullSearcher: Bitap.empty(), identifiers: null, tokens: [], words: [], options: FuzzyOptions()))
];
```
Won't work for
```dart
class _FuzzySearchTask<T extends Object> extends AsyncTask<_FuzzySearchTaskArgs<T>, List<Result<T>>> {
```

At the moment at looking up a `_FuzzySearchTask` of type `<User>` for example, it will fail because `_FuzzySearchTask<User>` is not registered.

**Comment by gmpassos** [comment]
Maybe this is a simple bug.

Can you make a simple project with a working example of this case?

Regards

**Comment by tomasweigenast** [comment]
@gmpassos it is not a bug. Its how Dart works. At the moment of registering the task, it gets registered as `_FuzzySearchTask<dynamic>`

**Comment by gmpassos** [comment]
Maybe we can workaround the Dart limitations. I just need a simple example to work on.
